---
# *============================================================================*
#                UNIVERSITY OF MELBOURNE RMARKDOWN THESIS
# *============================================================================*

# +----------------------------------------------------------------------------+
#  This bookdown template can be used to create a thesis for the University of
#  Melbourne.
#
#  This document defines all the metadata associated with the thesis in a YAML
#  (YAML Ain't Markup Language) header. Your text should be placed in other
#  RMarkdown documents (usually one per chapter). Edit the `_bookdown.yml` file
#  to change the order etc. of the other files. See
#  https://bookdown.org/yihui/bookdown/ for more details on how to use bookdown.
# +----------------------------------------------------------------------------+

# +----------------------------------------------------------------------------+
#  Changes:
#
#  2018-10-11 (Luke Zappia)
#    * Create first draft RMarkdown template file
# +----------------------------------------------------------------------------+

# *============================================================================*
#  TITLE PAGE
# *============================================================================*

# +-----Title------------------------------------------------------------------+

title: "Tools and techniques for single-cell RNA-seq data"

# +-----Author-----------------------------------------------------------------+
author: "Luke Zappia"
orcid: "0000-0001-7744-8565"

# +-----Degree-----------------------------------------------------------------+
degree: "Doctor of Philosophy"

# +-----Submission date--------------------------------------------------------+
#  By default these are set based on when the document is built but that they
#  also be manually controlled.
# +----------------------------------------------------------------------------+

submissionmonth: "`r format(Sys.Date(), '%B')`"
submissionyear: "`r format(Sys.Date(), '%Y')`"

# +-----Institute--------------------------------------------------------------+
#  Whatever is in the `department` field is placed first with the `university`
#  below it. If you are assoicated with multiple departments/institutes you
#  might need to adjust the format or consider how to include your information.
# +----------------------------------------------------------------------------+

department: "School of Biosciences"
university: "The University of Melbourne"

# +-----Statement--------------------------------------------------------------+

statement: |
  Submitted in Total Fulfillment of the Requirements of the Degree of Doctor of
  Philosophy

# *============================================================================*
#  FRONT MATTER
#
#  Other sections that come after the title page but before the main text.
#
#  By default these are pulled from other files (for PDF output) but they can
#  also be included directly here. Setting any of these sections to `FALSE` will
#  remove them from the final document.
# *============================================================================*

# +-----Abstract---------------------------------------------------------------+

abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("0-frontmatter/01-abstract.Rmd"), collapse = "\n  ")`

# +-----Declaration------------------------------------------------------------+

declaration: |
  `r if(knitr:::is_latex_output()) paste(readLines("0-frontmatter/02-declaration.Rmd"), collapse = "\n  ")`

# +-----Preface----------------------------------------------------------------+

preface: |
  `r if(knitr:::is_latex_output()) paste(readLines("0-frontmatter/03-preface.Rmd"), collapse = "\n  ")`

# +-----Acknowledgements-------------------------------------------------------+

acknowledgements: |
  `r if(knitr:::is_latex_output()) paste(readLines("0-frontmatter/04-acknowledgements.Rmd"), collapse = "\n  ")`

# +-----List of tables---------------------------------------------------------+
#  Should only be included if you have at least 10 tables
# +----------------------------------------------------------------------------+

lot: true

# +-----List of figures--------------------------------------------------------+
#  Should only be included if you have at least 10 figures
# +----------------------------------------------------------------------------+

lof: true

# *============================================================================*
#  CITATIONS
# *============================================================================*

# +-----Bibliography-----------------------------------------------------------+
#  Export your bibliography database as a bibtex file and refer to it here.
# +----------------------------------------------------------------------------+

bibliography: "bib/references.bib"

# +-----Citation style---------------------------------------------------------+
#  To change your citation style download a Citation Style Language file from
#  https://www.zotero.org/styles and refer to it to change the appearance of
#  your citations. See https://citationstyles.org/ for more details.
# +----------------------------------------------------------------------------+

csl: "style/genome-biology.csl"

# *============================================================================*
#  OUTPUT FORMATS
#
#  These options control the various output formats. You may be able to control
#  some things but editing these, other things will require editing the template
#  files or the underlying functions.
# *============================================================================*

knit: "bookdown::render_book"
site: "bookdown::bookdown_site"
output:
    bookdown::pdf_book:
        template: "style/template.tex"
        toc: true
        toc_depth: 3
        keep_tex: TRUE
        pandoc_args: [
            "--wrap", "none",
            "--top-level-division", "chapter"
        ]
    unimelbdown::thesis_gitbook: default
    unimelbdown::thesis_word:
        reference_docx: "style/template.docx"
        toc: true
        toc_depth: 3
        fig_caption: true
    unimelbdown::thesis_epub: default
---

```{r knitr-options, include = FALSE}
options(knitr.graphics.auto_pdf = TRUE)

knitr::opts_chunk$set(
  echo      = FALSE,
  warning   = FALSE,
  message   = FALSE,
  error     = FALSE,
  cache     = FALSE,
  fig.ext   = "png",
  fig.path  = "figures/",
  fig.align = "center",
  out.width = "80%"
)
```

```{r libraries}
# File paths
library("here")

# Plotting
library("ggplot2")
library("cowplot")
library("RColorBrewer")

# Clustering trees
library("clustree")

# JSON
library("jsonlite")

# Strings
library("stringr")

# File IO
library("readr")

# Manipulation
library("dplyr")
library("tidyr")
```

```{r source}
source("R/tools_plots.R")
source("R/utils.R")
```

```{r doctype}
tex  <- TRUE
docx <- FALSE
html <- FALSE

if (!knitr:::is_latex_output()) {
    tex <- FALSE
    if (knitr:::is_html_output()) {
        html <- TRUE
    } else {
        docx <- TRUE
    }
}
```

```{r palette}
pal <- c(pink   = "#EC008C", # Pink
         blue   = "#00ADEF", # Blue
         green  = "#8DC63F", # Green
         teal   = "#00B7C6", # Teal
         orange = "#F47920", # Orange
         purple = "#7A52C7", # Purple
         grey   = "#999999") # Grey

phase_pal <- c(brewer.pal(5, "Set1"), "#999999")
```

```{r load-tools}
tools <- read_json("data/tools-table.json", simplifyVector = TRUE) %>%
    select(-Refs) %>%
    mutate(Added = as.Date(Added),
           Updated = as.Date(Updated))

tools_date_counts <- tools %>%
    select(Date = Added) %>%
    group_by(Date = as.Date(Date)) %>%
    summarise(Count = n()) %>%
    complete(Date = full_seq(Date, 1), fill = list(Count = 0)) %>%
    mutate(Total = cumsum(Count))

cats <- read_json("data/cat-descriptions.json", simplifyVector = TRUE) %>%
    mutate(Phase = factor(Phase,
                          levels = c("Phase 1", "Phase 2", "Phase 3", "Phase 4",
                                     "Multiple", "Other")))

cat_counts <- tools %>%
    summarise_at(7:38, sum) %>%
    gather(key = Category, value = Count) %>%
    arrange(-Count, Category) %>%
    mutate(Prop = Count / nrow(tools)) %>%
    left_join(cats, by = "Category") %>%
    mutate(Category = str_replace_all(Category, "([[:upper:]])", " \\1")) %>%
    mutate(Category = str_trim(Category)) %>%
    mutate(Category = ifelse(Category == "U M Is", "UMIs", Category)) %>%
    mutate(Category = factor(Category, levels = Category))
```

```{r load-tools-analytics}
tools_users <- read_tsv(here("data/tools-users.tsv"),
                        col_types = cols(
                            .default = col_double(),
                            Date = col_date(format = "")
                        ))

tools_countries <- read_tsv(here("data/tools-countries.tsv"),
                            col_types = cols(
                                .default = col_character(),
                                Users = col_double()
                            )) %>%
    mutate(Country = case_when(
        Country == "Czechia"           ~ "Czech Republic",
        Country == "Macedonia (FYROM)" ~ "Macedonia",
        Country == "United Kingdom"    ~ "UK",
        Country == "United States"     ~ "USA",
        TRUE                           ~ Country
    ))
```

`r if(html) '# Front matter {-}'`
